export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SERVER_ERROR =  'SERVER_ERROR';

export const PROJECT_KIND_EXIST = 'PROJECT_KIND_EXIST';

export const PROJECT_KIND_INPUT_INVALID = 'PROJECT_KIND_INPUT_INVALID';

export const CREATE_PROJECT_KIND_SUCCESS = 'CREATE_PROJECT_KIND_SUCCESS';

export const FIND_PROJECT_KIND_FAILED = 'FIND_PROJECT_KIND_FAILED';

export const FIND_PROJECT_KIND_SUCCESS = 'FIND_PROJECT_KIND_SUCCESS';

export const UPDATE_PROJECT_KIND_FAILED = 'UPDATE_PROJECT_KIND_FAILED';

export const UPDATE_PROJECT_KIND_SUCCESS = 'UPDATE_PROJECT_KIND_SUCCESS';

export const DELETE_PROJECT_KIND_FAILED = 'DELETE_PROJECT_KIND_FAILED';

export const DELETE_PROJECT_KIND_SUCCESS = 'DELETE_PROJECT_KIND_SUCCESS';