//Common code
export const SERVER_ERROR =  'SERVER_ERROR';

//Login code
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ADMIN_EXIST = 'ADMIN_EXIST';

export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';

//Project kind code
export const PROJECT_KIND_EXIST = 'PROJECT_KIND_EXIST';

export const PROJECT_KIND_INPUT_INVALID = 'PROJECT_KIND_INPUT_INVALID';

export const CREATE_PROJECT_KIND_SUCCESS = 'CREATE_PROJECT_KIND_SUCCESS';

export const FIND_PROJECT_KIND_FAILED = 'FIND_PROJECT_KIND_FAILED';

export const FIND_PROJECT_KIND_SUCCESS = 'FIND_PROJECT_KIND_SUCCESS';

export const UPDATE_PROJECT_KIND_FAILED = 'UPDATE_PROJECT_KIND_FAILED';

export const UPDATE_PROJECT_KIND_SUCCESS = 'UPDATE_PROJECT_KIND_SUCCESS';

export const DELETE_PROJECT_KIND_FAILED = 'DELETE_PROJECT_KIND_FAILED';

export const DELETE_PROJECT_KIND_SUCCESS = 'DELETE_PROJECT_KIND_SUCCESS';

//Project status code
export const PROJECT_STATUS_INPUT_INVALID = 'PROJECT_STATUS_INPUT_INVALID';

export const PROJECT_STATUS_EXIST = 'PROJECT_STATUS_EXIST';

export const CREATE_PROJECT_STATUS_SUCCESS = 'CREATE_PROJECT_STATUS_SUCCESS';

export const FIND_PROJECT_STATUS_FAILED = 'FIND_PROJECT_STATUS_FAILED';

export const FIND_PROJECT_STATUS_SUCCESS= 'FIND_PROJECT_STATUS_SUCCESS';

export const UPDATE_PROJECT_STATUS_FAILED = 'UPDATE_PROJECT_STATUS_FAILED';

export const UPDATE_PROJECT_STATUS_SUCCESS = 'UPDATE_PROJECT_STATUS_SUCCESS';

export const DELETE_PROJECT_STATUS_FAILED = 'DELETE_PROJECT_STATUS_FAILED';

export const DELETE_PROJECT_STATUS_SUCCESS = 'DELETE_PROJECT_STATUS_SUCCESS';

//User group code

export const USER_GROUP_INPUT_INVALID = 'USER_GROUP_INPUT_INVALID';

export const USER_GROUP_EXIST = 'USER_GROUP_EXIST';

export const CREATE_USER_GROUP_SUCCESS = 'CREATE_USER_GROUP_SUCCESS';

export const FIND_USER_GROUP_FAILED = 'FIND_USER_GROUP_FAILED';

export const FIND_USER_GROUP_SUCCESS= 'FIND_USER_GROUP_SUCCESS';

export const UPDATE_USER_GROUP_FAILED = 'UPDATE_USER_GROUP_FAILED';

export const UPDATE_USER_GROUP_SUCCESS = 'UPDATE_USER_GROUP_SUCCESS';

export const DELETE_USER_GROUP_FAILED = 'DELETE_USER_GROUP_FAILED';

export const DELETE_USER_GROUP_SUCCESS = 'DELETE_USER_GROUP_SUCCESS';

//Tech stack code
export const TECH_STACK_INPUT_INVALID = 'TECH_STACK_INPUT_INVALID';

export const TECH_STACK_EXIST = 'TECH_STACK_EXIST';

export const CREATE_TECH_STACK_SUCCESS = 'CREATE_TECH_STACK_SUCCESS';

export const FIND_TECH_STACK_FAILED = 'FIND_TECH_STACK_FAILED';

export const FIND_TECH_STACK_SUCCESS= 'FIND_TECH_STACK_SUCCESS';

export const UPDATE_TECH_STACK_FAILED = 'UPDATE_TECH_STACK_FAILED';

export const UPDATE_TECH_STACK_SUCCESS = 'UPDATE_TECH_STACK_SUCCESS';

export const DELETE_TECH_STACK_FAILED = 'DELETE_TECH_STACK_FAILED';

export const DELETE_TECH_STACK_SUCCESS = 'DELETE_TECH_STACK_SUCCESS';

//Department

export const DEPARTMENT_INPUT_INVALID = 'DEPARTMENT_INPUT_INVALID';

export const DEPARTMENT_EXIST = 'DEPARTMENT_EXIST';

export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';

export const FIND_DEPARTMENT_FAILED = 'FIND_DEPARTMENT_FAILED';

export const FIND_DEPARTMENT_SUCCESS= 'FIND_DEPARTMENT_SUCCESS';

export const UPDATE_DEPARTMENT_FAILED = 'UPDATE_DEPARTMENT_FAILED';

export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';

export const DELETE_DEPARTMENT_FAILED = 'DELETE_DEPARTMENT_FAILED';

export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';

//Employee

export const EMPLOYEE_INPUT_INVALID = 'EMPLOYEE_INPUT_INVALID';

export const EMPLOYEE_EXIST = 'EMPLOYEE_EXIST';

export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';

export const FIND_EMPLOYEE_FAILED = 'FIND_EMPLOYEE_FAILED';

export const FIND_EMPLOYEE_SUCCESS= 'FIND_EMPLOYEE_SUCCESS';

export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED';

export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';

export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED';

export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';

//Project

export const PROJECT_INPUT_INVALID = 'PROJECT_INPUT_INVALID';

export const PROJECT_EXIST = 'PROJECT_EXIST';

export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';

export const FIND_PROJECT_FAILED = 'FIND_PROJECT_FAILED';

export const FIND_PROJECT_SUCCESS= 'FIND_PROJECT_SUCCESS';

export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';

export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';